### PR TITLE
Introduce EVMRuntime; expandable contract

### PR DESCRIPTION
**Pull request by pinkiebell**

### CODE REVIEW

**Comment by pinkiebell** [comment]
@peara @johannbarbie 
This has my other prs commits into it, but what do you think of moving all internal functions for the EVM into its own contract? 

I also moved the Runtime functions into the Verifier contract, in case we need more access in the future (likely).

- We don't have to change some 'execute' functions return struct everytime we need to change something.
- We can optimize hashing functions, as we now have direct access to the evm struct
- We can now override specific opcode handlers 👍

**Comment by peara** [comment]
@pinkiebell 
I like the idea but there is a risk of making Verifier contract become to big.
I this big contract is already an issue with EthereumRuntime already :thinking: 

If you really don't want to change the struct every time, then we can extend EthereumRuntime to implement a function which only return `hash`. 
Then the Verifier only interact with that contract.
What do you think?

**Comment by johannbarbie** [comment]
> We can now override specific opcode handlers

this is interesting, as we can mock the CALL opcodes for Plasma, while keeping a more general implementation of the runtime around.

> Verifier contract become to big

I'm also scared of that but lacking the knowledge to do a good assessment. 

> implement a function which only return hash.

wouldn't this be achieved by the [stateHash PR](https://github.com/leapdao/solEVM-enforcer/issues/4) anyways? 

> moved the Runtime functions into the Verifier contract, in case we need more access in the future 

the verifier only needs to execute single steps. would be awesome if EVMRuntime would only have a runtime function without `stepCount` param. and EthereumRuntime builds on that function to run multiple steps (if we even need that. i think the js runtime can take that over).

**Comment by pinkiebell** [comment]
Another thing that might be a advantage:
Assuming we have to change the verifier code in the future we also have to pay gas for the EVMRuntime. However, we can deploy those hot functions into its own contract and the general verifier 'shell' contracts calls those < which in turn we can set anytime. 

We gain booth now. Low gas costs for re-deploying decision logic and direct access to the evm

**Pull request merged**
