### PR TITLE
Rolling integration

### LINKED ISSUE #68: Refactor the fixtures
# Bounty
Refactor the fixtures.

Every value should be in a hexadecimal representation where appropriate and fixed size-types should always be padded to full representation (like memory, each slot 32 bytes, stack: uint256).

Example:
```
stack: ['64']
to
stack: ['0x0000000000000000000000000000000000000000000000000000000000000040']
```

## Deliverables
Makes it easier to reason about the fixtures.

## Gain for the project
🍌 🍌 ⌛️ 

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

### PR DESCRIPTION
**Pull request by pinkiebell**
- Correctly handle `PUSH` opcodes to right-pad with zero, both for on & offchain runtimes
- Introduce parts for upcoming Merkle Trees for memory, calldata etc (RangeProofHelper)
- Fix memory gas cost calculation for `MLOAD`  
- Change types for `mem` and `stack` to `bytes32[]`
- `AbstractMerkleTree` base class
- Add `MAX_MEM_WORD_COUNT = 256` to both evm runtimes. If we overcommit on memory size this should be an internal vm error. Provable on-chain
- `RangeProofHelper` for upcoming range proofs
- add `package.json` entry point for consumption of the js utils
- other small fixes along the way
- Import `PlasmaVerifier` contract, we are gonna use it in the future as a custom reference implementation

Fixes #68 as drive-by

Reviewer share: 20% @johannbarbie

### CODE REVIEW

**Comment by peara** [comment]
The parts which I can understand is good.
The parts which I'm not sure: `RangeProofHelper`. How the tree will look like? I wish there is a doc to explain it.
The parts I'm confused: `PlasmaVerifier`. So we will mock the call to external contracts. But it means we can only support ERC20, ERC721 and ERC1948 transactions, isn't it? And we have to mock all kind of functions existed in those tokens as well. I think it might be a bit too much to handle onchain.

**Comment by johannbarbie** [comment]
> I wish there is a doc to explain it.

@pinkiebell i wish so too :)

**Comment by johannbarbie** [comment]
> So we will mock the call to external contracts. But it means we can only support ERC20, ERC721 and ERC1948 transactions, isn't it? And we have to mock all kind of functions existed in those tokens as well. I think it might be a bit too much to handle onchain.

yes, that is basically the idea. but we start only with balanceOf and transfer. no allowance or other stuff. to enable basic functionality like in this game: https://github.com/leapdao/spending-conditions/blob/master/contracts/GameCondition.sol#L89-L91

**Comment by peara** [comment]
So it is indeed a lot.
But what if those `transfer` do something more?
Or we have to make sure that those are standard `transfer`.

**Comment by johannbarbie** [comment]
> Or we have to make sure that those are standard `transfer`.

yes, they only create new outputs in the transaction, we assume same implementation for all ERC20.

**Comment by pinkiebell** [comment]
> The parts which I'm not sure: RangeProofHelper. How the tree will look like? I wish there is a doc to explain it.

Docs are coming :). There is no special tree design, but we need to track access of
- read
- write
- length
- slice operations
 across all opcodes.  And also account for memory expansions which don't actually modify memory slots. Only expanding the size.

If we know all this, we can be smart and only send the data to the contract which is really needed, and the contract can verify those characteristics via access checks at the end.

**Pull request merged**
